language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
env:
  - DJANGO=1.4.16
  - DJANGO=1.5.11
  - DJANGO=1.6.8
  - DJANGO=1.7.1
matrix:
  exclude:
    - python: "3.2"
      env: DJANGO=1.4.16
    - python: "3.3"
      env: DJANGO=1.4.16
    - python: "2.6"
      env: DJANGO=1.7.1
# command to install dependencies
install:
  - pip install -q Django==$DJANGO --use-mirrors
  - python setup.py install
# command to run tests
script: python setup.py test
